#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dicho")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertuser(user instance);
  partial void Updateuser(user instance);
  partial void Deleteuser(user instance);
  partial void Insertcategory(category instance);
  partial void Updatecategory(category instance);
  partial void Deletecategory(category instance);
  partial void Insertproduct(product instance);
  partial void Updateproduct(product instance);
  partial void Deleteproduct(product instance);
  partial void Insertproduct_category(product_category instance);
  partial void Updateproduct_category(product_category instance);
  partial void Deleteproduct_category(product_category instance);
  partial void Insertproduct_file(product_file instance);
  partial void Updateproduct_file(product_file instance);
  partial void Deleteproduct_file(product_file instance);
  partial void Insertproduct_price_history(product_price_history instance);
  partial void Updateproduct_price_history(product_price_history instance);
  partial void Deleteproduct_price_history(product_price_history instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["dichoConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<user> users
	{
		get
		{
			return this.GetTable<user>();
		}
	}
	
	public System.Data.Linq.Table<category> categories
	{
		get
		{
			return this.GetTable<category>();
		}
	}
	
	public System.Data.Linq.Table<product> products
	{
		get
		{
			return this.GetTable<product>();
		}
	}
	
	public System.Data.Linq.Table<product_category> product_categories
	{
		get
		{
			return this.GetTable<product_category>();
		}
	}
	
	public System.Data.Linq.Table<product_file> product_files
	{
		get
		{
			return this.GetTable<product_file>();
		}
	}
	
	public System.Data.Linq.Table<product_price_history> product_price_histories
	{
		get
		{
			return this.GetTable<product_price_history>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[user]")]
public partial class user : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _user_id;
	
	private string _username;
	
	private string _password;
	
	private string _fullname;
	
	private string _avatar;
	
	private System.Nullable<System.DateTime> _create_date;
	
	private string _type;
	
	private string _role;
	
	private System.Nullable<bool> _is_active;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(long value);
    partial void Onuser_idChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnfullnameChanging(string value);
    partial void OnfullnameChanged();
    partial void OnavatarChanging(string value);
    partial void OnavatarChanged();
    partial void Oncreate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_dateChanged();
    partial void OntypeChanging(string value);
    partial void OntypeChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    partial void Onis_activeChanging(System.Nullable<bool> value);
    partial void Onis_activeChanged();
    #endregion
	
	public user()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public long user_id
	{
		get
		{
			return this._user_id;
		}
		set
		{
			if ((this._user_id != value))
			{
				this.Onuser_idChanging(value);
				this.SendPropertyChanging();
				this._user_id = value;
				this.SendPropertyChanged("user_id");
				this.Onuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="NVarChar(255)")]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="NVarChar(255)")]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fullname", DbType="NVarChar(255)")]
	public string fullname
	{
		get
		{
			return this._fullname;
		}
		set
		{
			if ((this._fullname != value))
			{
				this.OnfullnameChanging(value);
				this.SendPropertyChanging();
				this._fullname = value;
				this.SendPropertyChanged("fullname");
				this.OnfullnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_avatar", DbType="NVarChar(255)")]
	public string avatar
	{
		get
		{
			return this._avatar;
		}
		set
		{
			if ((this._avatar != value))
			{
				this.OnavatarChanging(value);
				this.SendPropertyChanging();
				this._avatar = value;
				this.SendPropertyChanged("avatar");
				this.OnavatarChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> create_date
	{
		get
		{
			return this._create_date;
		}
		set
		{
			if ((this._create_date != value))
			{
				this.Oncreate_dateChanging(value);
				this.SendPropertyChanging();
				this._create_date = value;
				this.SendPropertyChanged("create_date");
				this.Oncreate_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="NVarChar(255)")]
	public string type
	{
		get
		{
			return this._type;
		}
		set
		{
			if ((this._type != value))
			{
				this.OntypeChanging(value);
				this.SendPropertyChanging();
				this._type = value;
				this.SendPropertyChanged("type");
				this.OntypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="NVarChar(255)")]
	public string role
	{
		get
		{
			return this._role;
		}
		set
		{
			if ((this._role != value))
			{
				this.OnroleChanging(value);
				this.SendPropertyChanging();
				this._role = value;
				this.SendPropertyChanged("role");
				this.OnroleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_is_active", DbType="Bit")]
	public System.Nullable<bool> is_active
	{
		get
		{
			return this._is_active;
		}
		set
		{
			if ((this._is_active != value))
			{
				this.Onis_activeChanging(value);
				this.SendPropertyChanging();
				this._is_active = value;
				this.SendPropertyChanged("is_active");
				this.Onis_activeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.category")]
public partial class category : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _category_id;
	
	private int _type;
	
	private string _category_name;
	
	private string _category_description;
	
	private System.DateTime _created_date;
	
	private int _sort_order;
	
	private string _icon;
	
	private string _status;
	
	private EntitySet<product_category> _product_categories;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncategory_idChanging(int value);
    partial void Oncategory_idChanged();
    partial void OntypeChanging(int value);
    partial void OntypeChanged();
    partial void Oncategory_nameChanging(string value);
    partial void Oncategory_nameChanged();
    partial void Oncategory_descriptionChanging(string value);
    partial void Oncategory_descriptionChanged();
    partial void Oncreated_dateChanging(System.DateTime value);
    partial void Oncreated_dateChanged();
    partial void Onsort_orderChanging(int value);
    partial void Onsort_orderChanged();
    partial void OniconChanging(string value);
    partial void OniconChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
	
	public category()
	{
		this._product_categories = new EntitySet<product_category>(new Action<product_category>(this.attach_product_categories), new Action<product_category>(this.detach_product_categories));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int category_id
	{
		get
		{
			return this._category_id;
		}
		set
		{
			if ((this._category_id != value))
			{
				this.Oncategory_idChanging(value);
				this.SendPropertyChanging();
				this._category_id = value;
				this.SendPropertyChanged("category_id");
				this.Oncategory_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_type", DbType="Int NOT NULL")]
	public int type
	{
		get
		{
			return this._type;
		}
		set
		{
			if ((this._type != value))
			{
				this.OntypeChanging(value);
				this.SendPropertyChanging();
				this._type = value;
				this.SendPropertyChanged("type");
				this.OntypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_name", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
	public string category_name
	{
		get
		{
			return this._category_name;
		}
		set
		{
			if ((this._category_name != value))
			{
				this.Oncategory_nameChanging(value);
				this.SendPropertyChanging();
				this._category_name = value;
				this.SendPropertyChanged("category_name");
				this.Oncategory_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_description", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
	public string category_description
	{
		get
		{
			return this._category_description;
		}
		set
		{
			if ((this._category_description != value))
			{
				this.Oncategory_descriptionChanging(value);
				this.SendPropertyChanging();
				this._category_description = value;
				this.SendPropertyChanged("category_description");
				this.Oncategory_descriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="DateTime NOT NULL")]
	public System.DateTime created_date
	{
		get
		{
			return this._created_date;
		}
		set
		{
			if ((this._created_date != value))
			{
				this.Oncreated_dateChanging(value);
				this.SendPropertyChanging();
				this._created_date = value;
				this.SendPropertyChanged("created_date");
				this.Oncreated_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sort_order", DbType="Int NOT NULL")]
	public int sort_order
	{
		get
		{
			return this._sort_order;
		}
		set
		{
			if ((this._sort_order != value))
			{
				this.Onsort_orderChanging(value);
				this.SendPropertyChanging();
				this._sort_order = value;
				this.SendPropertyChanged("sort_order");
				this.Onsort_orderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_icon", DbType="NVarChar(256)")]
	public string icon
	{
		get
		{
			return this._icon;
		}
		set
		{
			if ((this._icon != value))
			{
				this.OniconChanging(value);
				this.SendPropertyChanging();
				this._icon = value;
				this.SendPropertyChanged("icon");
				this.OniconChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NChar(10)")]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="category_product_category", Storage="_product_categories", ThisKey="category_id", OtherKey="category_id")]
	public EntitySet<product_category> product_categories
	{
		get
		{
			return this._product_categories;
		}
		set
		{
			this._product_categories.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_product_categories(product_category entity)
	{
		this.SendPropertyChanging();
		entity.category = this;
	}
	
	private void detach_product_categories(product_category entity)
	{
		this.SendPropertyChanging();
		entity.category = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product")]
public partial class product : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _product_id;
	
	private decimal _price;
	
	private string _product_name;
	
	private string _product_description;
	
	private string _unit;
	
	private string _note;
	
	private string _image_thumbnail;
	
	private System.DateTime _created_date;
	
	private string _status;
	
	private EntitySet<product_category> _product_categories;
	
	private EntitySet<product_price_history> _product_price_histories;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_idChanging(long value);
    partial void Onproduct_idChanged();
    partial void OnpriceChanging(decimal value);
    partial void OnpriceChanged();
    partial void Onproduct_nameChanging(string value);
    partial void Onproduct_nameChanged();
    partial void Onproduct_descriptionChanging(string value);
    partial void Onproduct_descriptionChanged();
    partial void OnunitChanging(string value);
    partial void OnunitChanged();
    partial void OnnoteChanging(string value);
    partial void OnnoteChanged();
    partial void Onimage_thumbnailChanging(string value);
    partial void Onimage_thumbnailChanged();
    partial void Oncreated_dateChanging(System.DateTime value);
    partial void Oncreated_dateChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    #endregion
	
	public product()
	{
		this._product_categories = new EntitySet<product_category>(new Action<product_category>(this.attach_product_categories), new Action<product_category>(this.detach_product_categories));
		this._product_price_histories = new EntitySet<product_price_history>(new Action<product_price_history>(this.attach_product_price_histories), new Action<product_price_history>(this.detach_product_price_histories));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public long product_id
	{
		get
		{
			return this._product_id;
		}
		set
		{
			if ((this._product_id != value))
			{
				this.Onproduct_idChanging(value);
				this.SendPropertyChanging();
				this._product_id = value;
				this.SendPropertyChanged("product_id");
				this.Onproduct_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(18,0) NOT NULL")]
	public decimal price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this.OnpriceChanging(value);
				this.SendPropertyChanging();
				this._price = value;
				this.SendPropertyChanged("price");
				this.OnpriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string product_name
	{
		get
		{
			return this._product_name;
		}
		set
		{
			if ((this._product_name != value))
			{
				this.Onproduct_nameChanging(value);
				this.SendPropertyChanging();
				this._product_name = value;
				this.SendPropertyChanged("product_name");
				this.Onproduct_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_description", DbType="NVarChar(1000)")]
	public string product_description
	{
		get
		{
			return this._product_description;
		}
		set
		{
			if ((this._product_description != value))
			{
				this.Onproduct_descriptionChanging(value);
				this.SendPropertyChanging();
				this._product_description = value;
				this.SendPropertyChanged("product_description");
				this.Onproduct_descriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unit", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
	public string unit
	{
		get
		{
			return this._unit;
		}
		set
		{
			if ((this._unit != value))
			{
				this.OnunitChanging(value);
				this.SendPropertyChanging();
				this._unit = value;
				this.SendPropertyChanged("unit");
				this.OnunitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_note", DbType="NVarChar(255)")]
	public string note
	{
		get
		{
			return this._note;
		}
		set
		{
			if ((this._note != value))
			{
				this.OnnoteChanging(value);
				this.SendPropertyChanging();
				this._note = value;
				this.SendPropertyChanged("note");
				this.OnnoteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image_thumbnail", DbType="NVarChar(255)")]
	public string image_thumbnail
	{
		get
		{
			return this._image_thumbnail;
		}
		set
		{
			if ((this._image_thumbnail != value))
			{
				this.Onimage_thumbnailChanging(value);
				this.SendPropertyChanging();
				this._image_thumbnail = value;
				this.SendPropertyChanged("image_thumbnail");
				this.Onimage_thumbnailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="DateTime NOT NULL")]
	public System.DateTime created_date
	{
		get
		{
			return this._created_date;
		}
		set
		{
			if ((this._created_date != value))
			{
				this.Oncreated_dateChanging(value);
				this.SendPropertyChanging();
				this._created_date = value;
				this.SendPropertyChanged("created_date");
				this.Oncreated_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="NChar(10)")]
	public string status
	{
		get
		{
			return this._status;
		}
		set
		{
			if ((this._status != value))
			{
				this.OnstatusChanging(value);
				this.SendPropertyChanging();
				this._status = value;
				this.SendPropertyChanged("status");
				this.OnstatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_product_category", Storage="_product_categories", ThisKey="product_id", OtherKey="product_id")]
	public EntitySet<product_category> product_categories
	{
		get
		{
			return this._product_categories;
		}
		set
		{
			this._product_categories.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_product_price_history", Storage="_product_price_histories", ThisKey="product_id", OtherKey="product_id")]
	public EntitySet<product_price_history> product_price_histories
	{
		get
		{
			return this._product_price_histories;
		}
		set
		{
			this._product_price_histories.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_product_categories(product_category entity)
	{
		this.SendPropertyChanging();
		entity.product = this;
	}
	
	private void detach_product_categories(product_category entity)
	{
		this.SendPropertyChanging();
		entity.product = null;
	}
	
	private void attach_product_price_histories(product_price_history entity)
	{
		this.SendPropertyChanging();
		entity.product = this;
	}
	
	private void detach_product_price_histories(product_price_history entity)
	{
		this.SendPropertyChanging();
		entity.product = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product_category")]
public partial class product_category : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _product_id;
	
	private int _category_id;
	
	private EntityRef<category> _category;
	
	private EntityRef<product> _product;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_idChanging(long value);
    partial void Onproduct_idChanged();
    partial void Oncategory_idChanging(int value);
    partial void Oncategory_idChanged();
    #endregion
	
	public product_category()
	{
		this._category = default(EntityRef<category>);
		this._product = default(EntityRef<product>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
	public long product_id
	{
		get
		{
			return this._product_id;
		}
		set
		{
			if ((this._product_id != value))
			{
				if (this._product.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onproduct_idChanging(value);
				this.SendPropertyChanging();
				this._product_id = value;
				this.SendPropertyChanged("product_id");
				this.Onproduct_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int category_id
	{
		get
		{
			return this._category_id;
		}
		set
		{
			if ((this._category_id != value))
			{
				if (this._category.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Oncategory_idChanging(value);
				this.SendPropertyChanging();
				this._category_id = value;
				this.SendPropertyChanged("category_id");
				this.Oncategory_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="category_product_category", Storage="_category", ThisKey="category_id", OtherKey="category_id", IsForeignKey=true)]
	public category category
	{
		get
		{
			return this._category.Entity;
		}
		set
		{
			category previousValue = this._category.Entity;
			if (((previousValue != value) 
						|| (this._category.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._category.Entity = null;
					previousValue.product_categories.Remove(this);
				}
				this._category.Entity = value;
				if ((value != null))
				{
					value.product_categories.Add(this);
					this._category_id = value.category_id;
				}
				else
				{
					this._category_id = default(int);
				}
				this.SendPropertyChanged("category");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_product_category", Storage="_product", ThisKey="product_id", OtherKey="product_id", IsForeignKey=true)]
	public product product
	{
		get
		{
			return this._product.Entity;
		}
		set
		{
			product previousValue = this._product.Entity;
			if (((previousValue != value) 
						|| (this._product.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._product.Entity = null;
					previousValue.product_categories.Remove(this);
				}
				this._product.Entity = value;
				if ((value != null))
				{
					value.product_categories.Add(this);
					this._product_id = value.product_id;
				}
				else
				{
					this._product_id = default(long);
				}
				this.SendPropertyChanged("product");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product_file")]
public partial class product_file : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _product_id;
	
	private string _file_id;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_idChanging(long value);
    partial void Onproduct_idChanged();
    partial void Onfile_idChanging(string value);
    partial void Onfile_idChanged();
    #endregion
	
	public product_file()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
	public long product_id
	{
		get
		{
			return this._product_id;
		}
		set
		{
			if ((this._product_id != value))
			{
				this.Onproduct_idChanging(value);
				this.SendPropertyChanging();
				this._product_id = value;
				this.SendPropertyChanged("product_id");
				this.Onproduct_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_file_id", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string file_id
	{
		get
		{
			return this._file_id;
		}
		set
		{
			if ((this._file_id != value))
			{
				this.Onfile_idChanging(value);
				this.SendPropertyChanging();
				this._file_id = value;
				this.SendPropertyChanged("file_id");
				this.Onfile_idChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.product_price_history")]
public partial class product_price_history : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private long _product_price_history_id;
	
	private long _product_id;
	
	private System.Nullable<decimal> _price;
	
	private System.DateTime _created_date;
	
	private System.Nullable<System.DateTime> _modify_date;
	
	private string _unit;
	
	private EntityRef<product> _product;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproduct_price_history_idChanging(long value);
    partial void Onproduct_price_history_idChanged();
    partial void Onproduct_idChanging(long value);
    partial void Onproduct_idChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    partial void Oncreated_dateChanging(System.DateTime value);
    partial void Oncreated_dateChanged();
    partial void Onmodify_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onmodify_dateChanged();
    partial void OnunitChanging(string value);
    partial void OnunitChanged();
    #endregion
	
	public product_price_history()
	{
		this._product = default(EntityRef<product>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_price_history_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public long product_price_history_id
	{
		get
		{
			return this._product_price_history_id;
		}
		set
		{
			if ((this._product_price_history_id != value))
			{
				this.Onproduct_price_history_idChanging(value);
				this.SendPropertyChanging();
				this._product_price_history_id = value;
				this.SendPropertyChanged("product_price_history_id");
				this.Onproduct_price_history_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_product_id", DbType="BigInt NOT NULL")]
	public long product_id
	{
		get
		{
			return this._product_id;
		}
		set
		{
			if ((this._product_id != value))
			{
				if (this._product.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onproduct_idChanging(value);
				this.SendPropertyChanging();
				this._product_id = value;
				this.SendPropertyChanged("product_id");
				this.Onproduct_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Money")]
	public System.Nullable<decimal> price
	{
		get
		{
			return this._price;
		}
		set
		{
			if ((this._price != value))
			{
				this.OnpriceChanging(value);
				this.SendPropertyChanging();
				this._price = value;
				this.SendPropertyChanged("price");
				this.OnpriceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_date", DbType="DateTime NOT NULL")]
	public System.DateTime created_date
	{
		get
		{
			return this._created_date;
		}
		set
		{
			if ((this._created_date != value))
			{
				this.Oncreated_dateChanging(value);
				this.SendPropertyChanging();
				this._created_date = value;
				this.SendPropertyChanged("created_date");
				this.Oncreated_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modify_date", DbType="DateTime")]
	public System.Nullable<System.DateTime> modify_date
	{
		get
		{
			return this._modify_date;
		}
		set
		{
			if ((this._modify_date != value))
			{
				this.Onmodify_dateChanging(value);
				this.SendPropertyChanging();
				this._modify_date = value;
				this.SendPropertyChanged("modify_date");
				this.Onmodify_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unit", DbType="NVarChar(255)")]
	public string unit
	{
		get
		{
			return this._unit;
		}
		set
		{
			if ((this._unit != value))
			{
				this.OnunitChanging(value);
				this.SendPropertyChanging();
				this._unit = value;
				this.SendPropertyChanged("unit");
				this.OnunitChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="product_product_price_history", Storage="_product", ThisKey="product_id", OtherKey="product_id", IsForeignKey=true)]
	public product product
	{
		get
		{
			return this._product.Entity;
		}
		set
		{
			product previousValue = this._product.Entity;
			if (((previousValue != value) 
						|| (this._product.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._product.Entity = null;
					previousValue.product_price_histories.Remove(this);
				}
				this._product.Entity = value;
				if ((value != null))
				{
					value.product_price_histories.Add(this);
					this._product_id = value.product_id;
				}
				else
				{
					this._product_id = default(long);
				}
				this.SendPropertyChanged("product");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
