<?xml version="1.0" encoding="utf-8"?><Database Name="dicho" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=long-pc;Initial Catalog=dicho;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="dichoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.[user]" Member="users">
    <Type Name="user">
      <Column Name="user_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="fullname" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="avatar" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="create_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="type" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="role" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="is_active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.category" Member="categories">
    <Type Name="category">
      <Column Name="category_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="category_name" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="category_description" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="sort_order" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="icon" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="category_product_category" Member="product_categories" ThisKey="category_id" OtherKey="category_id" Type="product_category" />
    </Type>
  </Table>
  <Table Name="dbo.product" Member="products">
    <Type Name="product">
      <Column Name="product_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="price" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="product_name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="product_description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="unit" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="note" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="image_thumbnail" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Association Name="product_product_category" Member="product_categories" ThisKey="product_id" OtherKey="product_id" Type="product_category" />
      <Association Name="product_product_price_history" Member="product_price_histories" ThisKey="product_id" OtherKey="product_id" Type="product_price_history" />
    </Type>
  </Table>
  <Table Name="dbo.product_category" Member="product_categories">
    <Type Name="product_category">
      <Column Name="product_id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="category_id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="category_product_category" Member="category" ThisKey="category_id" OtherKey="category_id" Type="category" IsForeignKey="true" />
      <Association Name="product_product_category" Member="product" ThisKey="product_id" OtherKey="product_id" Type="product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.product_file" Member="product_files">
    <Type Name="product_file">
      <Column Name="product_id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="file_id" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.product_price_history" Member="product_price_histories">
    <Type Name="product_price_history">
      <Column Name="product_price_history_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="product_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="price" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="created_date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modify_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="unit" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="product_product_price_history" Member="product" ThisKey="product_id" OtherKey="product_id" Type="product" IsForeignKey="true" />
    </Type>
  </Table>
</Database>